#!/bin/sh

panic() {
	echo $* >&2
	exit 1
}

# locate base paths
if [ "$0" = "genci" ] && [ -z "$GENCI_HOME"] || [ "$0" = "/usr/local/bin/genci" ] && [ -z "$GENCI_HOME" ]; then
	GENCI=/usr/local/bin/genci

	LIB=/usr/local/lib/genci
	EXAMPLES=/usr/local/share/examples/genci
	DOC=/usr/local/share/doc/genci
else
	if [ ! -z "$GENCI_HOME" ]; then
		prefix=$GENCI_HOME
	else
		prefix=$(dirname $0)
	fi

	GENCI=$prefix/genci

	LIB=$prefix/lib
	EXAMPLES=$prefix/examples
	DOC=$prefix/doc
fi

# locate config paths
if [ "$(id -u)" = 0 ] || [ -z "$HOME" ] || [ "$GENCI_GLOBAL" = "yes" ]; then
	CONF=/etc/genci
	WORKS=/var/lib/genci
	LOGS=/var/log/genci
else
	CONF=$HOME/.genci
	WORKS=$CONF/works
	LOGS=$CONF/logs
fi

# basic argument sanitizing
if [ $# -eq 0 ]; then
	echo "generic-ci - a generic continuous integration tool"
	echo
	echo "Find more help under http://trustedco.de/generic-ci/"
	echo
	echo
	cat $DOC/LICENSE
	exit 1
fi

# command detection (top or sub)
COMMAND=$1
if [ -f $LIB/top-$COMMAND.sh ]; then
	command_script=$LIB/top-$COMMAND.sh

	# execute directly, nothing more todo
	. $command_script
	exit $?
elif [ -f $LIB/sub-$COMMAND.sh ]; then
	command_script=$LIB/sub-$COMMAND.sh
else
	echo "Command $1 not found!" >&2
	panic "Usage:  $0 <command>"
fi

# only sub commands go here

# load the configuration
CONFIG=$2
config_file=$CONF/$CONFIG
if [ ! -f $config_file ]; then
	echo "Configuration $CONFIG not found!" >&2
	panic "Usage:  $0 <command> <configuration>"
fi
. $config_file

# set up more base paths
WORK=$WORKS/$CONFIG

REPOSITORY=$WORK/repository
BUILDS=$WORK/builds
HEADS=$WORK/heads
RELEASES=$WORK/releases

mkdir -p $WORK $BUILDS $HEADS $RELEASES

# check for repository and clone on demand
if [ ! -d $REPOSITORY ] && [ "$COMMAND" != "init" ]; then
	echo "Configuration is not initialized! Use '$0 init $CONFIG <source>'." >&2
	exit 1
fi
GIT="git --git-dir=$REPOSITORY"

# finally run the command
. $command_script
exit $?
