#!/bin/sh

# search for library path
if [ -z "$GITCE_HOME" ]; then
	if [ -z "$(echo $0 | grep '/')" ] || [ "$0" = "/usr/local/bin/gitce" ]; then
		# assume we're called through the PATH
		GITCE_HOME=/usr/local
	else
		GITCE_HOME=$(dirname $0)
	fi
fi

if [ -f $GITCE_HOME/lib/init.sh ]; then
	LIB=$GITCE_HOME/lib
elif [ -f $GITCE_HOME/lib/gitce/init.sh ]; then
	LIB=$GITCE_HOME/lib/gitce
elif [ -f $GITCE_HOME/../lib/init.sh ]; then
	GITCE_HOME=$(dirname $GITCE_HOME)
	LIB=$GITCE_HOME/lib
elif [ -f $GITCE_HOME/../lib/gitce/init.sh ]; then
	GITCE_HOME=$(dirname $GITCE_HOME)
	LIB=$GITCE_HOME/lib/gitce
else
	echo "GITCE_HOME[$GITCE_HOME] not found!" >&2
	exit 1
fi


# version
if [ "$1" = "version" ]; then
	VERSION_FILE=$GITCE_HOME/share/gitce/VERSION
	if [ -f $VERSION_FILE ]; then
		cat $VERSION_FILE
	else
		echo "development"
	fi
	exit 0
fi

# basic argument sanitizing
if [ $# -lt 2 ]; then
	cat $LIB/help.txt
	exit 1
fi

# run the requested command
COMMAND=$1
COMMAND_SCRIPT=$LIB/gitce-$COMMAND.sh
if [ -f $COMMAND_SCRIPT ]; then
	. $LIB/init.sh
	. $COMMAND_SCRIPT $*
else
	echo "Command $COMMAND not found!" >&2
	exit 1
fi
