#!/bin/sh
CONFIG=$1
SOURCE=$2

# dummy config
dummy=$CONFIG-second

fail() {
	rm $HOME/.genci/$dummy
	rm -rf $HOME/.genci/works/$dummy
	exit $1
}

# generate new config
touch $HOME/.genci/$dummy

# should not work
$GENCI init $dummy /unexistant || fail 0

rm $HOME/.genci/$dummy
rm -rf $HOME/.genci/works/$dummy
exit 1
