#!/bin/sh
CONFIG=$1
SOURCE=$2

GIT="git --git-dir=$SOURCE/.git"
ls -l $SOURCE

# create a branch
$GIT branch testbranch

$GENCI update $CONFIG

# build the branches
$GENCI run $CONFIG testbranch

# now delete the branch
$GIT branch -d testbranch

# update repository
$GENCI update $CONFIG

# now there should be only one line, mentioning the deletion
[ $($GENCI pending $CONFIG | wc -l) -eq 2 ] || exit 1
[ ! -z "$($GENCI pending $CONFIG | grep "delete testbranch")" ] || exit 2

exit 0
