#!/bin/sh
CONFIG=$1

$GENCI release $CONFIG || exit 1

if [ ! -z "$($GENCI pending $CONFIG | grep "^release master")" ]; then
	exit 0
else
	exit 2
fi

output=$($GENCI run $CONFIG | grep "DUMMY RELEASE")

if [ ! -z "$output" ]; then
	exit 0
else
	exit 3
fi
