#!/bin/sh
CONFIG=$1

# only one line, since we only have a simpe master
[ $($GENCI status $CONFIG | wc -l) -eq 1 ] || exit 1

# this one line should be a mark to build the master
[ ! -z "$($GENCI status $CONFIG | grep "^ok master build 0 $")" ] || exit 2

exit 0
