#!/bin/sh
CONFIG=$1

$GENCI watch $CONFIG

if [ "$($GENCI status $CONFIG)" != "ok master active 0 " ]; then
	exit 1
fi


$GENCI watch $CONFIG

if [ "$($GENCI status $CONFIG)" != "ok master active 0 " ]; then
	exit 1
fi

exit 0
