#!/bin/sh

# do not start automatically
if [ -f /etc/init.d/gitce-watchers ]; then
    # remove update script
    update-rc.d -f gitce-watchers remove
fi

# stop gitce
/etc/init.d/gitce-watchers stop
